server:
  port: 10086

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 43.138.179.248
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        max-wait: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.179.248:3306/xpeng?characterEncoding=utf-8&useSSL=false&serverTimezon=GMT%2B8 #mysql8以上要配置时区，东八区
    username: root
    password: Root@123456

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 600
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true

mybatis:
  # 加载配置文件
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/login"
      - "/auth/register"
      - "/defect/notoken"